spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 777540849916-ute25p2ero608q03jjis5i0dg2d7dn94.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    hikari:
      username: root
      password: password

jwt:
  secret: outstagram-asjhrcoawechsel4vtuh4esulvbhse4thvsk4
